USE MASTER
GO

CREATE DATABASE ExamManagementDB
GO

USE ExamManagementDB
GO
CREATE TABLE USERACCOUNTS
(
	PERSONALID VARCHAR (10),
	PASS VARCHAR (50) NOT NULL,
	USERLEVEL INT DEFAULT 0 NOT NULL, -- 0 = AD , 1 = TEACHER , 2 = STUDENT
	EMAIL VARCHAR (50) NOT NULL,
	CONSTRAINT PK_USERACCOUNT PRIMARY KEY (PERSONALID)

)

CREATE TABLE CLASSES
(
	CLASSID VARCHAR (10),
	CLASSNAME NVARCHAR(50) NOT NULL,
	GRADEID VARCHAR(10) NOT NULL,
	QUANTITY INT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_CLASS PRIMARY KEY (CLASSID)
)

CREATE TABLE GRADE
(
	GRADEID VARCHAR(10),
	DISPLAYNAME NVARCHAR(100) NOT NULL

	CONSTRAINT PK_GRADE PRIMARY KEY(GRADEID)
)

CREATE TABLE SUBJECTS
(
	SUBJECTID VARCHAR(10),
	SUBJECTNAME NVARCHAR (100) NOT NULL,
	CONSTRAINT PK_SUBJECT PRIMARY KEY (SUBJECTID)
)

CREATE TABLE STUDENTS
(
	PERSONALID VARCHAR (10),
	FULLNAME NVARCHAR (100) NOT NULL,
	GENDER NVARCHAR(100) NOT NULL,
	CLASSID VARCHAR (10),
	DATEOFBIRTH DATE NOT NULL,	
	ISPRO INT NOT NULL,
	ADR NVARCHAR (100) NOT NULL,
	CONSTRAINT PK_STUDENT PRIMARY KEY (PERSONALID)
)

CREATE TABLE TEACHERS
(
	PERSONALID VARCHAR (10),
	FULLNAME NVARCHAR (100) NOT NULL,
	GENDER NVARCHAR(100) NOT NULL,
	CLASSID VARCHAR (10),
	SUBJECTID VARCHAR (10),
	DATEOFBIRTH DATE NOT NULL,
	ADR NVARCHAR (100) NOT NULL,
	CONSTRAINT PK_TEACHER PRIMARY KEY (PERSONALID)
)

CREATE TABLE ADMINISTRATORS
(
	PERSONALID VARCHAR (10),
	FULLNAME NVARCHAR (100) NOT NULL,
	GENDER NVARCHAR(100) NOT NULL,
	DATEOFBIRTH DATE,
	ADMINONLYKEY VARCHAR (100) NOT NULL,
	ADR NVARCHAR (100) NOT NULL,
	CONSTRAINT PK_ADMINISTRATOR PRIMARY KEY (PERSONALID)
)

CREATE TABLE TRAINING
(
	TRAININGID VARCHAR (10),
	PERSONALID VARCHAR (10),
	OVERALLPROPERBILITY FLOAT DEFAULT 0.0 NOT NULL, --0.1 = 10%
	TOTALCOMPLETED INT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_TRAINING PRIMARY KEY (TRAININGID)

)

CREATE TABLE TRAININGHISTORY
(
	TRAININGID VARCHAR (10),
	PERSONALID VARCHAR (10),
	TOPICID VARCHAR (10) NOT NULL,
	TRAININGDATE DATE DEFAULT GETDATE(),
	RESULT NVARCHAR (10) NOT NULL,
	OVERALLPROPERBILITY FLOAT DEFAULT 0.0 NOT NULL, 
	TOTALCORRECT INT DEFAULT 0 NOT NULL,
	TOTALINCORRECT INT DEFAULT 0 NOT NULL,
	CONSTRAINT PK_TRAININGHISTORY PRIMARY KEY (TRAININGID , TOPICID , PERSONALID)

)

CREATE TABLE TESTS
(
	TESTID VARCHAR (10),
	PERSONALID VARCHAR (10),
	TOPICID VARCHAR (10),
	COMPLETESTATUS INT DEFAULT 0 NOT NULL,
	DATEOFTEST DATE NOT NULL,
	TIMELEFT INT DEFAULT -1 NOT NULL,
	CONSTRAINT PK_TEST PRIMARY KEY (TESTID)
)

CREATE TABLE PROCESSES
(
	TESTID VARCHAR (10),
	QUESTIONID VARCHAR (10) NOT NULL,
	CHOICE VARCHAR (10) DEFAULT NULL,	
	CONSTRAINT PK_PROCESS PRIMARY KEY (TESTID , QUESTIONID)

)

CREATE TABLE STATISTIC
(
	TESTID VARCHAR(10),
	QUESTIONID VARCHAR(10),
	ISCORRECT INT,  -- 0 LÀ ĐÚNG , 1 LÀ SAI
	CONSTRAINT PK_STATISTIC PRIMARY KEY(TESTID , QUESTIONID) 
)

-- TABLE FROM NG0C--




CREATE TABLE RESULTOFTEST
(
	TESTID VARCHAR(10),
	TOTALCORRECT INT DEFAULT 0 NOT NULL,
	TOTALINCORRECT INT DEFAULT 0 NOT NULL,
	SCORE FLOAT DEFAULT 0 NOT NULL,
	PASSSTATUS NVARCHAR(100) DEFAULT N'rớt' NOT NULL,

	CONSTRAINT PK_RESULTOFTEST PRIMARY KEY (TESTID)
)

CREATE TABLE TOPIC
(
	TOPICID VARCHAR(10),
	SUBJECTID VARCHAR(10),
	GRADEID VARCHAR(10),
	TOTALTIME INT NOT NULL, --thời gian làm bài

	CONSTRAINT PK_TOPIC PRIMARY KEY(TOPICID)
)

CREATE TABLE TOPIC_DETAILS
(
	TOPICID VARCHAR(10),
	QUESTIONID VARCHAR(10),
	NOTES NVARCHAR(100) --ALLOW NULL

	CONSTRAINT PK_TOPIC_DETAILS PRIMARY KEY(TOPICID, QUESTIONID)
)

CREATE TABLE SEMESTER
(
	SEMESTERID VARCHAR(10),
	NAME NVARCHAR(100)

	CONSTRAINT PK_SEMESTER PRIMARY KEY (SEMESTERID)
)

CREATE TABLE EXAM
(
	EXAMID VARCHAR(10),
	SEMESTER VARCHAR(10),
	YEAROFSEMESTER INT DEFAULT YEAR(SYSDATETIME()) NOT NULL,
	TYPEOFEXAM INT NOT NULL, --THI GIẢ THI THẬT: 1 LÀ THẬT, 0 LÀ GIẢ
	STATUSOFEXAM INT NOT NULL, --TÌNH TRẠNG KÌ THI ĐÃ THI CHƯA, 1 LÀ RỒI, 0 LÀ CHƯA
	DATEOFEXAM DATE NOT NULL,

	CONSTRAINT PK_EXAM PRIMARY KEY(EXAMID)
)

CREATE TABLE EXAM_DETAILS
(
	EXAMID VARCHAR(10),
	PERSONALID VARCHAR(10),
	TOPICID VARCHAR(10),

	CONSTRAINT PK_EXAM_DETAILS PRIMARY KEY (EXAMID, PERSONALID, TOPICID)
)

CREATE TABLE SCHEDULE -- LỊCH THI CHO HỌC SINH XEM
(
	PERSONALID VARCHAR(10),
	EXAMID VARCHAR(10),
	SUBJECTID VARCHAR(10),
	DATEOFTEST DATE DEFAULT SYSDATETIME() NOT NULL,
	NAMEOFSUBJECT NVARCHAR(100) NOT NULL,
	PLACE NVARCHAR(100) DEFAULT N'chưa xác định' NOT NULL

	CONSTRAINT PK_SCHEDULE PRIMARY KEY(PERSONALID, EXAMID, SUBJECTID)
)

CREATE TABLE QUESTIONSSTORAGE
(
	PERSONALID VARCHAR(10),--NGƯỜI ĐÓNG GÓP CÂU HỎI
	QUESTIONID VARCHAR(10),
	APPROVALSTATUS INT DEFAULT 0 NOT NULL, --TÌNH TRẠNG CÂU HỎI ĐƯỢC DUYỆT HAY CHƯA, 0 LÀ CHƯA, 1 LÀ RỒI

	CONSTRAINT PK_QUESTIONSSTORAGE PRIMARY KEY(PERSONALID, QUESTIONID)
)

CREATE TABLE QUESTION
(
	QUESTIONID VARCHAR(10),
	GRADEID VARCHAR(10) NOT NULL,
	SUBJECTID VARCHAR(10) NOT NULL,
	CONTENTOFQUESTION NVARCHAR(3600) NOT NULL,
	A NVARCHAR(1000) NOT NULL,
	B NVARCHAR(1000) NOT NULL,
	C NVARCHAR(1000) NOT NULL,
	D NVARCHAR(1000) NOT NULL,
	E NVARCHAR(1000) DEFAULT '' NOT NULL, --E VÀ F SẼ TÙY CÂU HỎI MỚI CÓ
	F NVARCHAR(1000) DEFAULT '' NOT NULL,
	CORRECTANSWER VARCHAR(10) NOT NULL, --'A' hay là 'B' ...
	HINT NVARCHAR(1000) NOT NULL,
	DIFFICULT INT DEFAULT 1 NOT NULL, -- ĐỘ KHÓ CỦA CÂU HỎI: 1 =DỄ, 2 = TRUNG BÌNH, 3 = KHÓ
	ISPRO INT NOT NULL, -- ĐỀ CHUYÊN HAY KHÔNG 1 LÀ PRO, 0 LÀ KHÔNG PRO
	
	CONSTRAINT PK_QUESTION PRIMARY KEY(QUESTIONID)
)

CREATE TABLE PERCENTAGEOFQUESTION
(
	QUESTIONID VARCHAR(10),
	EXAMID VARCHAR(10),
	TOTALCORRECT INT DEFAULT 0 NOT NULL,
	TOTALINCORRECT INT DEFAULT 0 NOT NULL,

	CONSTRAINT PK_PERCENT_QUESTION PRIMARY KEY (QUESTIONID, EXAMID)
)

CREATE TABLE PERMISSION
(
	PERMISSIONID INT,
	PERMISSIONNAME NVARCHAR (100) NOT NULL,
	CONSTRAINT PK_PERMISSION PRIMARY KEY (PERMISSIONID)
)


















